### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by linzhongchen** [OpenFirework/Retinaface_CPP#1]
make RetinaFace_MNN 

问题如下：
IlmThread.cpp:(.text._ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJMN16IlmThread_opencv6ThreadEFvvEPS4_EEEEED0Ev[_ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJMN16IlmThread_opencv6ThreadEFvvEPS4_EEEEED5Ev]+0x17)：对‘std::thread::_State::~_State()’未定义的引用
./linux_x86_64/opencv-3.4.7/share/OpenCV/3rdparty/lib/libIlmImf.a(IlmThread.cpp.o)：在函数‘IlmThread_opencv::Thread::start()’中：
IlmThread.cpp:(.text._ZN16IlmThread_opencv6Thread5startEv+0x69)：对‘std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())’未定义的引用
./linux_x86_64/opencv-3.4.7/share/OpenCV/3rdparty/lib/libIlmImf.a(IlmThread.cpp.o):(.data.rel.ro._ZTINSt6thread11_State_implINS_8_InvokerISt5tupleIJMN16IlmThread_opencv6ThreadEFvvEPS4_EEEEEE[_ZTINSt6thread11_State_implINS_8_InvokerISt5tupleIJMN16IlmThread_opencv6ThreadEFvvEPS4_EEEEEE]+0x10)：对‘typeinfo for std::thread::_State’未定义的引用
collect2: error: ld returned 1 exit status
Makefile:33: recipe for target 'RetinaFace_NCNN' failed
make: *** [RetinaFace_NCNN] Error 1

我的编译环境是按照MNN安装的

**Comment by ABlueLight** [comment]
@linzhongchen  是在哪个系统上编译的，gcc版本是啥。因为我是在ubuntu 20.0上编译的MNN、Opencv库，编译器版本比较新。在旧gcc的版本上可能会有不兼容的情况～
